### ISSUE TITLE
Leading whitespace in the default value of the atto_fontfamily/fontselectlist settings

### ISSUE THREAD

**Issue by mudrd8mz** [projectestac/moodle-atto_fontfamily#1]
The leading spaces from the `settings.php` are used in the textarea, too. It probably does not harm the functionality but it would look better without it.

![atto_fontfamily](https://cloud.githubusercontent.com/assets/85831/7714493/519f4d62-fe7f-11e4-88c0-f1f0605fc65d.png)

**Comment by crazyserver** [comment]
Thanks David,
I've take advantage of this issue to choose some other default fonts...

Cheers!
