### ISSUE TITLE
Auto update on 3.11

### ISSUE THREAD

**Issue by wbuk** [projectestac/moodle-atto_fontfamily#10]
Hi 

I try to update Moodle most weeks with the weekly bug fix release.  I have loads of plugins Every plugin that is set to work with 3.11 installs during the installation but any that are not down to work with 3.11 do not and have to be installed manually.  I did have 51 plugins that had to be installed manually, taking ages.  Having contacted many developers, they have just adjusted the tag to say it support 3.11, like yours Font Family etc for ATTO does and now I only have to install 8, yours being one of them.    If you could do with ATTO font size, font family etc, that would be so very very useful.  Thank you so much.

**Comment by toniginard** [comment]
I have set the tags for Moodle 3.8 to 3.11 for this plugin in the Moodle repository (https://moodle.org/plugins/atto_fontfamily). We only have three plugins registered and they all have the 3.11 tag.

Best wishes.
