### ISSUE TITLE
Moodle 4

### ISSUE THREAD

**Issue by wbuk** [projectestac/moodle-atto_fontfamily#11]
Hi, you were so kind as to update the version number on the font family.  We are now on moodle 4 and need the version number changed to moodle 4.

**Comment by toniginard** [comment]
Hi @wbuk,

We have added 4.0 as a supported version in the plugins database. Is that what you needed?


Best wishes.

**Comment by jarvil1** [comment]
Will this support Moodle 4.1? @toniginard

**Comment by haiksu** [comment]
4.1 version support would be highly appreciated.

**Comment by toniginard** [comment]
Hi @Urpokarhu1 and @haiksu,

Sorry for the late reply. I have just released a new version tagged for Moodle up to 4.4.


Best wishes,
