### ISSUE TITLE
Auto Update

### ISSUE THREAD

**Issue by wbuk** [projectestac/moodle-atto_fontfamily#13]
Big ask, but any chance you can update the supported version number on the moodle database to 4.3+.  FontFamily does work on 4.3+.  We update moodle every week and FontFamily has to be installed manually as moodle thinks it only works up to version 4.0.  If you increase the supported version to latest it will install automatically upon upgrade, saving a lot of time. Cheers.

**Comment by toniginard** [comment]
Hi, @wbuk,

I have just added versions 4.1, 4.2, 4.3 and 4.4 to the list of supported versions.


Best wishes,
