### ISSUE TITLE
changing fontFamily only works for selected text

### ISSUE THREAD

**Issue by nbawzl2004** [projectestac/moodle-atto_fontfamily#2]
I have download and install the plugin from https://moodle.org/plugins/view/atto_fontfamily
However, there is a issue.
At the beginning, without changing anything, I type "abcd", It appears to be 
![default](https://cloud.githubusercontent.com/assets/6826647/8294752/60664858-18f3-11e5-9834-b6e4c7fa7efa.png)
Then I input "enter" change the cursor to second line, and then I click "Courier"
![clickcourier](https://cloud.githubusercontent.com/assets/6826647/8294764/7cf1d46a-18f3-11e5-9bb0-3ce74a8fac16.png)
And type "abcd", it appears like this:
![keep the same](https://cloud.githubusercontent.com/assets/6826647/8294778/8c6dda10-18f3-11e5-988b-1e0b7e04c83b.png)
Which was not shown in "Courier" family.
Then I select part of the text in second line like this 
![choose text to change](https://cloud.githubusercontent.com/assets/6826647/8294788/95f01d5a-18f3-11e5-8dd4-5e2d00c29661.png)
And click "Courier" button. Now the selected text becomes appeared in "Courier" family.
![after changed](https://cloud.githubusercontent.com/assets/6826647/8294792/9ea263c2-18f3-11e5-86db-a69d52da52f9.png)
I try this on every available font family. They behave the same. 
Is this plugin only working for selected text?  Or there is some setting I need to do?

**Comment by toniginard** [comment]
Hi!

This issue was opened a long time ago, so sorry for being ignored for so long.
Yes, this plugin only woks on selected text. We have no plans to change that behaviour.

Best wishes,
