### ISSUE TITLE
Dropdown list persists

### ISSUE THREAD

**Issue by tonyfinlay** [projectestac/moodle-atto_fontfamily#4]
Sometimes after using the font picker the drop-down persists on screen, this is an intermittent issue and it has been experienced on a few devices.

![font-selection](https://cloud.githubusercontent.com/assets/1906561/14492184/9019049e-0175-11e6-9f76-b0b02ffd5d9d.jpg)

**Comment by sarjona** [comment]
Hi!
Thanks for your comment! :-)
What versions of Moodle you found this error? Which theme are you using?
Best wishes from Barcelona!
Sara

**Comment by toniginard** [comment]
I think three years and a half waiting for an answer is enough, so I close this issue.
